### ISSUE TITLE
Mkfifo is failing with "Operation not supported" when files are on windows share

### ISSUE THREAD

**Issue by rosen-vladimirov** [NativeScript/ios-sim-portable#31]
When you try starting ios simulator on Mac, but the app that will be loaded in the simulator is on Windows share (or any other place where mkfifo cannot be executed), the code is failing with error: 

```
mkfifo: <appPath>/platforms/ios/build/emulator/.<appname>.log: Operation not supported
```

The problem is that `mkfifo` is not supported at all on Windows share and cannot create the file there.
Instead of writing the file in the `<appPath>/platforms/ios/build/emulator/`, we should create it in the `/tmp` folder.

**Comment by Fatme** [comment]
Workaround:

`tns emulate ios --justlaunch`

**Comment by Fatme** [comment]
Related: https://github.com/NativeScript/nativescript-cli/issues/1058
